export const requiredFieldsByCategory = {
    Рамки: [
      "productName",
      "productCategory",
      "productMaterial",
      "productType",
      "productWidth",
      "productHeight",
      "productPrice",
      "productDescription",
      "productImage",
    ],
    Профили: [
      "productName",
      "productCategory",
      "productMaterial",
      "productType",
      "productWidth",
      "productHeight",
      "productPrice",
      "productDescription",
      "productImage",
    ],
    Паспарту: [
      "productName",
      "productCategory",
      "productMaterial",
      "productWidth",
      "productHeight",
      "productPrice",
      "productDescription",
      "productImage",
    ],
    Гоблени: [
      "productName",
      "productCategory",
      "productType",
      "productWidth",
      "productHeight",
      "productPrice",
      "productDescription",
      "productImage",
    ],
    Пана: [
      "productName",
      "productCategory",
      "productWidth",
      "productHeight",
      "productPrice",
      "productDescription",
      "productImage",
    ],
    Огледала: [
      "productName",
      "productCategory",
      "productWidth",
      "productHeight",
      "productPrice",
      "productDescription",
      "productImage",
    ],
    Икони: [
      "productName",
      "productCategory",
      "productWidth",
      "productHeight",
      "productPrice",
      "productDescription",
      "productImage",
    ],
    "Арт материали": [
      "productName",
      "productCategory",
      "productPrice",
      "productDescription",
      "productImage",
    ],
  };